### ISSUE TITLE
Improve GUI Interface

### ISSUE THREAD

**Issue by jrcryan** [UCSB-CS56-Projects/cs56-games-simon-says#20]
Update GUI. Current game screen is small and cramped. 

Game instructions are in a scrollable box but a larger screen format could make them more readable. 

The option to "Choose Version" may be better called "Choose Difficulty" or "Choose Level"
Once a version is chosen it starts a new game, but perhaps this should be integrated into the single "New Game" button

Improve overall appearance of game; buttons could also have better graphics, set minimum screen size 

~150 points

**Comment by drewtaylors** [comment]
- Centered every screen in the game to appear in the middle of the computer screen rather than the top left corner
- Enlarged all screens
- Adjusted main menu buttons and rules to reflect the enlarging of screens
- Adjusted game buttons sizes and distancing from each other to be more aesthetically pleasing
- Removed choose version button and redirected New Game to request which level the user wants to play (this does not affect clicking a new game while already playing)

(requesting ~200 points total)

**Comment by drewtaylors** [comment]
63471cc098b37eb525eb2c2541a0140ba0acf441

**Comment by hannavigil** [comment]
Approve
